### ISSUE TITLE
Logout on dashboard

### ISSUE THREAD

**Issue by panjenny0** [nwplus/livesite#118]
- [x] logout on firebase auth
- [x] change route to starting screen (i.e. login)
<img width="204" alt="Screen Shot 2020-11-21 at 4 24 34 PM" src="https://user-images.githubusercontent.com/38872354/99890611-0c2b5080-2c16-11eb-8f36-c4fdb5ac1a5e.png">

**Comment by kevin-zou** [comment]
@panjenny0 By "functionality included" does that mean it should log the user out of their session? If so, is this blocked by the auth tasks?

**Comment by panjenny0** [comment]
@kevin-zou Good question! Yea it means logging the user out of their current session. I think this is technically blocked by both the auth task and the routing. I will have a PR for routing done either today or tomorrow so maybe to get started, you could just do the router part and once the auth is done, you can add the sign out on firebase :) 
How it was done in the CMS was something like
```
          await firebase.auth().signOut();
          router.push('/');
```
in https://github.com/nwplus/CMS-V2/blob/master/pages/index.js

**Comment by panjenny0** [comment]
closed by #184

**Comment by ianmah** [comment]
184?

**Comment by panjenny0** [comment]
> 184?
> 

I saw the logout button had been added, maybe this wasn't added in #184 but it worked in that PR

**Comment by ianmah** [comment]
oh haha Allison did it with Dan in a different PR

**Comment by panjenny0** [comment]
> oh haha Allison did it with Dan in a different PR

Oh HAHA okay nice whoops my bad 😬 good job Dan!!

**Comment by acchiang** [comment]
no our bad for forgetting to attach the pr here! ty

**Comment by acchiang** [comment]
HEADS UP, logging out redirects back to dashboard because there are dashboard features a logged out user can use
