### ISSUE TITLE
Set application deadline

### ISSUE THREAD

**Issue by panjenny0** [nwplus/livesite#120]
- [ ] add new field in featureFlags in the CMS: applicationDeadline (set this as timestamp)
- [ ] allow applications to be submitted on the hacker app until the deadline (i.e. lock after deadline)
<img width="352" alt="Screen Shot 2020-11-28 at 1 03 50 PM" src="https://user-images.githubusercontent.com/38872354/100526047-52366600-317a-11eb-8606-cfa43b567621.png">

**Comment by Ciuffi** [comment]
I think its best if we close it manually tbh, we can always prune anyone who submitted later but in the past we've kept it open a little longer if we needed more apps.
