### ISSUE TITLE
Set when to release applications tab

### ISSUE THREAD

**Issue by panjenny0** [nwplus/livesite#131]
- [ ] Add new field in feature flags in the CMS: `applicationsOpen` (as timestamp)
- [ ] Hacker app: don't release application tab until this date in production but always show this tab in dev

in `src/components/Sidebar.js` line 100, add release check here
```
  // List the application as the last item on the menu
  links.push({ location: '/application', text: 'APPLICATION' })
```
current feature flags
<img width="352" alt="Screen Shot 2020-11-28 at 1 03 50 PM" src="https://user-images.githubusercontent.com/38872354/100526088-a3def080-317a-11eb-8a2f-728e89f9be11.png">

**Comment by Ciuffi** [comment]
closed by #171
