### ISSUE TITLE
Add max size to file upload

### ISSUE THREAD

**Issue by kozr** [nwplus/livesite#224]
Currently, you're able to upload files of any size. To prevent people from maliciously uploading textbooks files or even movies. We should check and limit file size to something like 3-5MB before uploading it.

![image](https://user-images.githubusercontent.com/40312631/102035594-90847580-3d75-11eb-82bf-fbadcb2ae688.png)

**Comment by acchiang** [comment]
current file validations with PR 226: max 2mb and PDF files only
