### ISSUE TITLE
Feedback Reporting

### ISSUE THREAD

**Issue by JPGarCar** [nwplus/livesite#247]
Allow hackers to report a grade for another peer.

Our idea: There is a report button under every grade, when the button gets clicked the grade will be flagged for us to review. We would then review it on our admin panel and either keep it or remove it.

It would be nice to have the following information on the admin panel when reviewing the grade:
- the grade (all numbers and the comments)
-  who made the grade
- who was the grade for
- the project that was graded
- the average of the other grades for that project ??*Super extra

What could we do from this panel:
- remove the grade
- disqualify the grader and thus its team
- do nothing and close the report

**Comment by ianmah** [comment]
This ticket:

Add the "report" button from the owner's of that project
Create a table in judging/admin to view a list of all grades (and reported grades are flagged)
