### ISSUE TITLE
Email not found

### ISSUE THREAD

**Issue by Chr-N** [nwplus/livesite#276]
## Expected Behavior
Submitting my email to https://portal.nwplus.io/submission should link my Devpost to portal.

## Current Behavior
Email not found.

![image](https://user-images.githubusercontent.com/55326143/104136347-4f6a8b80-534a-11eb-8927-da6b6a4981e2.png)

## Steps to Reproduce

1. Visit https://portal.nwplus.io/submission 
2. Enter email
3. Click on "Link Devpost"

**Comment by jackyzha0** [comment]
it be like that sometimes 😔

**Comment by Chr-N** [comment]
ok 😢
