### ISSUE TITLE
Hacker Application > Page 1

### ISSUE THREAD

**Issue by anneguo3** [nwplus/livesite#285]
- Q1: Switch "preferred" to "full legal" and add optional "Middle Name" field (update validation as required)
- Q2: Add in text box for the "Other" selection -> check Q14: How did you hear about nwHacks? for an example of an other selection text box
- Q3: Add in text box for the "Other" selection (similar to above)
- Q4: Update date to "January 15th, 2022"
- Move Q10 to top of Part 2
- Remove Q12
- Add question at the end of this section: "This year, nwHacks is back in-person! To ensure everyone's safety, we will be checking for the proof of vaccination and your ID at sign-in. Will you double vaccinated by January 15, 2022?" with radio button yes/no
- -> if no, then next should bring them to an error page with the following copy: 
``` 
Sorry, due to British Columbia's Provincial Health Regulation, we are only accepting hackers who are/will be double-vaccinated by the day of nwHacks.

Thank you for your interest, and hope to see you again next year!
```

**Comment by phoenixthefirebird** [comment]
![image](https://user-images.githubusercontent.com/55338489/142365478-740a4369-116d-40ab-993d-66f01fbab4de.png)
