### ISSUE TITLE
Hacker App > Confirmation Page

### ISSUE THREAD

**Issue by anneguo3** [nwplus/livesite#292]
1. Remove 2021 nwHacks logo from the login page and the confirmation page
2. Retrieve logos displayed on the confirmation page from the Firebase sponsors collection

**Comment by panjenny0** [comment]
Additional details:
<hr/>
Regarding 1.

[S] Remove nwHacks2021 logo lockup in [src/containers/Landing/index.js](https://github.com/nwplus/livesite/blob/main/src/containers/Landing/index.js#L144)
- Delete logo_lockup image defined at the top of the file
- Delete `StyledLogoLockup`
- Screenshot (on /application/confirmation): <img width="600" alt="Screen Shot 2021-11-09 at 7 01 59 PM" src="https://user-images.githubusercontent.com/38872354/141041865-79405b5b-20e3-4275-8516-66ba51b7c04d.png">

<hr />
Regarding 2.

Currently, sponsor images are hard-coded in [src/containers/Landing/Footer.js](https://github.com/nwplus/livesite/blob/main/src/containers/Landing/Footer.js#L81-L86). We should grab these images from [firebase storage](https://console.firebase.google.com/u/0/project/nwplus-ubc-dev/storage/nwplus-ubc-dev.appspot.com/files/~2Fsponsor)
