### ISSUE TITLE
Portal > Consolidate Firebase fetch to one place

### ISSUE THREAD

**Issue by anneguo3** [nwplus/livesite#294]
Remove duplicate code of fetching from firebase

**Comment by panjenny0** [comment]
Not sure what this ticket entailed so I left it as it is - I think what we meant was this #299 right?

**Comment by anneguo3** [comment]
@panjenny0 I thought there was duplicate code for how we access Firebase?

**Comment by panjenny0** [comment]
Closing as wont-do - covered by #299
