### ISSUE TITLE
Hacker App > Firebase

### ISSUE THREAD

**Issue by anneguo3** [nwplus/livesite#295]
Add collections to hold all hacker applications with appropriate schema definitions

**Comment by panjenny0** [comment]
Already added in staging and prod! 
Current prod: https://console.firebase.google.com/u/0/project/nwplus-ubc-dev/firestore/data/~2FHackathons~2FnwHacks2022~2FApplicants
@anneguo3 I'll close this but feel free to re-open if you think this needs to be addressed still
