### ISSUE TITLE
replace validation error alert on the application page with an error popup/message

### ISSUE THREAD

**Issue by phoenixthefirebird** [nwplus/livesite#309]
![image](https://user-images.githubusercontent.com/55338489/142365311-81193534-e38e-40ec-9066-f76541801f90.png)
The application page currently shows an alert when there are required fields that are not filled out, change this to an error message/popup instead. Need design input @anneguo3

**Comment by panjenny0** [comment]
Already addressed by #289. Closing but feel free to re-open if this does not address what you were thinking.

**Comment by phoenixthefirebird** [comment]
It is! My bad I didn't look through the issues carefully, closing
