### ISSUE TITLE
Quicklink Card

### ISSUE THREAD

**Issue by ianmah** [nwplus/livesite#35]
Our [Quicklinks ](https://live.nwplus.io/quicklinks) page is going to have cards that contain a title and a list of links.

![image](https://user-images.githubusercontent.com/11839441/94361214-910b4b00-0067-11eb-987c-cf1deec5ce02.png)

In this ticket:
- Create a component that uses two `props`, called `title` and `links`, where `title` is a string and `links` is an array
- example links array:
```
[
  {
    href: 'https://google.com/',
    label: 'Google'
  },
  {
    href: 'https://github.com/',
    label: 'GitHub'
]
```
- This component should use the `Card` component
  - an example usage is here: https://github.com/nwplus/livesite/blob/03292b5b166a4aa1676292b12cf3d3765595228f/src/pages/Charcuterie.js#L21-L26
   - to see what this looks like in action, see https://live.nwplus.io/charcuterie

**Comment by shravani05** [comment]
Can I work on this issue?

**Comment by ianmah** [comment]
This one's been assigned already sorry @shravani05

**Comment by shravani05** [comment]
Okay, no problem @ianmah
