### ISSUE TITLE
Quicklinks Page

### ISSUE THREAD

**Issue by ianmah** [nwplus/livesite#37]
This ticket is to build the Quicklinks page. It depends on the quicklinks card being finished #35 

- Create a card for each quicklink category
- The quicklinks data will be available as a prop called `links`
  - `links` is an array of links, each link has the form
```
{
    href: 'https://www.google.com/',
    label: 'Google'
}
```
- Example of sorting items into categories: https://github.com/nwplus/livesite/blob/4616cc69e6107a89ea05b8867cf1f4ae97726daa/src/components/Faq.js#L41-L44

![image](https://user-images.githubusercontent.com/11839441/94371715-647a2200-00ad-11eb-9b71-dda8a8731ad5.png)

**Comment by jackyzha0** [comment]
this is done right @ianmah
