### ISSUE TITLE
Dynamic sidebar image

### ISSUE THREAD

**Issue by ianmah** [nwplus/livesite#39]
The image in the sidebar is currently hardcoded to the nwHacks image. We should get the image dynamically from the CMS.

![image](https://user-images.githubusercontent.com/11839441/94373720-128cc880-00bc-11eb-862c-134b18da7e2c.png)

- The code for the image is located in the sidebar component:

https://github.com/nwplus/livesite/blob/master/src/components/Sidebar.js#L62

- There are multiple examples of getting data from firebase here:
https://github.com/nwplus/livesite/tree/master/src/containers
- The image URL is available under `imgUrl` in the document called `Livesite`, which is part of the `collection` called `InternalWebsites`
![image](https://user-images.githubusercontent.com/11839441/95643109-c0578a00-0a61-11eb-8b09-ad23103b7500.png)

Relevant docs:
https://firebase.google.com/docs/firestore/query-data/get-data

**Comment by jackyzha0** [comment]
during scoping meeting, realized this feature is not super critical and probably adds more user friction than benefit (the ~1s loading period for the image doesn't look too hot)
