### ISSUE TITLE
Login & confirmation screens - routing with no authentication

### ISSUE THREAD

**Issue by ianmah** [nwplus/livesite#48]
- [ ] Build only the screens with no authentication required
- [ ] Setup routing for login and confirmed

#### login screen
<img width="701" alt="Screen Shot 2020-11-21 at 2 49 44 PM" src="https://user-images.githubusercontent.com/38872354/99889328-d338af00-2c08-11eb-91a5-8bc9fe0b39c2.png">

#### confirmation screen
<img width="568" alt="Screen Shot 2020-11-21 at 3 03 50 PM" src="https://user-images.githubusercontent.com/38872354/99889499-c452fc00-2c0a-11eb-8717-93fd95004983.png">

**Comment by ianmah** [comment]
![image](https://user-images.githubusercontent.com/11839441/97770625-2fb91a80-1af2-11eb-9552-309d50ddf137.png)

**Comment by acchiang** [comment]
Hey @panjenny0 @ianmah we missed mobile accessibility here, do we want that? If yes please file an issue, I can take a look

**Comment by panjenny0** [comment]
Good catch @acchiang - my bad I totally rushed through the two pages. I've assigned you to #155, thank you 🙏
