### ISSUE TITLE
Judging Card

### ISSUE THREAD

**Issue by ianmah** [nwplus/livesite#54]
- should take props for `imageUrl`, `teamName`, `description` etc
- Should use either `CardLike` or 'Card' in `./components`
- Use `Button` component

![image](https://user-images.githubusercontent.com/11839441/97770690-c08ff600-1af2-11eb-8643-6a5e10dcf24f.png)

**Comment by acchiang** [comment]
I thought were weren't getting hackers to upload pics? where would the picture come from

**Comment by ianmah** [comment]
YouTube thumbnail
