### ISSUE TITLE
Buttons, not including selects

### ISSUE THREAD

**Issue by panjenny0** [nwplus/livesite#80]
<img width="753" alt="Screen Shot 2020-11-09 at 10 01 08 AM" src="https://user-images.githubusercontent.com/38872354/98578665-7e914d80-2272-11eb-9b5a-bfeb42f865d6.png">
https://www.figma.com/file/49ZpQPySx3Rd9hmTvEqOpj/Hacker-Application?node-id=124%3A709

**Comment by acchiang** [comment]
new designs
![image](https://user-images.githubusercontent.com/47487758/99891502-36cdd700-2c1f-11eb-98d0-3258c5228160.png)

**Comment by acchiang** [comment]
bumping this up to a 2pt because there are a hecka bunch of specs from the designs that were not implemented yet

**Comment by panjenny0** [comment]
Agree this should be 2pt!
Also, do you mind making this smaller variant too for the edit button? Sorry to add this so last-minute 😓 
<img width="805" alt="Screen Shot 2020-11-21 at 11 48 16 PM" src="https://user-images.githubusercontent.com/38872354/99898122-0a807d80-2c54-11eb-938c-2893292a1a6d.png">

<img width="182" alt="Screen Shot 2020-11-21 at 11 47 37 PM" src="https://user-images.githubusercontent.com/38872354/99898106-f0df3600-2c53-11eb-874d-4cc7e931c146.png">
<img width="249" alt="Screen Shot 2020-11-21 at 11 47 47 PM" src="https://user-images.githubusercontent.com/38872354/99898113-f9377100-2c53-11eb-9bcf-a3db8c08b4ab.png">
