### ISSUE TITLE
Form part 3 (ending questionnaire) - no state and validation

### ISSUE THREAD

**Issue by panjenny0** [nwplus/livesite#92]
- [x] components only, no state or input validation
- [x] no need to include header, progress bar, next/back buttons at the bottom
<img width="677" alt="Screen Shot 2020-11-21 at 4 09 18 PM" src="https://user-images.githubusercontent.com/38872354/99890430-e8ffa180-2c13-11eb-884c-9c485f48ec90.png">

**Comment by kevin-zou** [comment]
Additional request:
- [ ] Add question for whether hackers opt in for getting swag (just stickers)

**Comment by panjenny0** [comment]
> Additional request:
> 
> * [ ]  Add question for whether hackers opt in for getting swag (just stickers)

@kevin-zou just a heads up! u might need to update the db schema https://github.com/nwplus/database-schemas and add the field to the ApplicationTemplate in `src/utility/Constants.js` too (unless you were already planning on doing it then thank you!)

**Comment by kevin-zou** [comment]
Thanks for the heads up! I did not do this but it looks like Giulio did! I might need to make changes to this but maybe in review we can find some way of avoiding it.
